#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LanguageCenter")]
	public partial class LanguageCenterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertATTENDANCE(ATTENDANCE instance);
    partial void UpdateATTENDANCE(ATTENDANCE instance);
    partial void DeleteATTENDANCE(ATTENDANCE instance);
    partial void InsertCLASS(CLASS instance);
    partial void UpdateCLASS(CLASS instance);
    partial void DeleteCLASS(CLASS instance);
    partial void InsertCLASS_MATERIAL(CLASS_MATERIAL instance);
    partial void UpdateCLASS_MATERIAL(CLASS_MATERIAL instance);
    partial void DeleteCLASS_MATERIAL(CLASS_MATERIAL instance);
    partial void InsertCLASS_SCHEDULE(CLASS_SCHEDULE instance);
    partial void UpdateCLASS_SCHEDULE(CLASS_SCHEDULE instance);
    partial void DeleteCLASS_SCHEDULE(CLASS_SCHEDULE instance);
    partial void InsertCLASS_STATUS(CLASS_STATUS instance);
    partial void UpdateCLASS_STATUS(CLASS_STATUS instance);
    partial void DeleteCLASS_STATUS(CLASS_STATUS instance);
    partial void InsertCONSULTATION(CONSULTATION instance);
    partial void UpdateCONSULTATION(CONSULTATION instance);
    partial void DeleteCONSULTATION(CONSULTATION instance);
    partial void InsertPAYMENT(PAYMENT instance);
    partial void UpdatePAYMENT(PAYMENT instance);
    partial void DeletePAYMENT(PAYMENT instance);
    partial void InsertPLACEMENT_TEST(PLACEMENT_TEST instance);
    partial void UpdatePLACEMENT_TEST(PLACEMENT_TEST instance);
    partial void DeletePLACEMENT_TEST(PLACEMENT_TEST instance);
    partial void InsertPROGRAM(PROGRAM instance);
    partial void UpdatePROGRAM(PROGRAM instance);
    partial void DeletePROGRAM(PROGRAM instance);
    partial void InsertREGISTRATION(REGISTRATION instance);
    partial void UpdateREGISTRATION(REGISTRATION instance);
    partial void DeleteREGISTRATION(REGISTRATION instance);
    partial void InsertSTUDENT(STUDENT instance);
    partial void UpdateSTUDENT(STUDENT instance);
    partial void DeleteSTUDENT(STUDENT instance);
    partial void InsertSTUDENT_FEEDBACK(STUDENT_FEEDBACK instance);
    partial void UpdateSTUDENT_FEEDBACK(STUDENT_FEEDBACK instance);
    partial void DeleteSTUDENT_FEEDBACK(STUDENT_FEEDBACK instance);
    partial void InsertTEACHER(TEACHER instance);
    partial void UpdateTEACHER(TEACHER instance);
    partial void DeleteTEACHER(TEACHER instance);
    partial void InsertUSER_ACCOUNT(USER_ACCOUNT instance);
    partial void UpdateUSER_ACCOUNT(USER_ACCOUNT instance);
    partial void DeleteUSER_ACCOUNT(USER_ACCOUNT instance);
    #endregion
		
		public LanguageCenterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LanguageCenterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LanguageCenterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LanguageCenterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ATTENDANCE> ATTENDANCEs
		{
			get
			{
				return this.GetTable<ATTENDANCE>();
			}
		}
		
		public System.Data.Linq.Table<CLASS> CLASSes
		{
			get
			{
				return this.GetTable<CLASS>();
			}
		}
		
		public System.Data.Linq.Table<CLASS_MATERIAL> CLASS_MATERIALs
		{
			get
			{
				return this.GetTable<CLASS_MATERIAL>();
			}
		}
		
		public System.Data.Linq.Table<CLASS_SCHEDULE> CLASS_SCHEDULEs
		{
			get
			{
				return this.GetTable<CLASS_SCHEDULE>();
			}
		}
		
		public System.Data.Linq.Table<CLASS_STATUS> CLASS_STATUS
		{
			get
			{
				return this.GetTable<CLASS_STATUS>();
			}
		}
		
		public System.Data.Linq.Table<CONSULTATION> CONSULTATIONs
		{
			get
			{
				return this.GetTable<CONSULTATION>();
			}
		}
		
		public System.Data.Linq.Table<PAYMENT> PAYMENTs
		{
			get
			{
				return this.GetTable<PAYMENT>();
			}
		}
		
		public System.Data.Linq.Table<PLACEMENT_TEST> PLACEMENT_TESTs
		{
			get
			{
				return this.GetTable<PLACEMENT_TEST>();
			}
		}
		
		public System.Data.Linq.Table<PROGRAM> PROGRAMs
		{
			get
			{
				return this.GetTable<PROGRAM>();
			}
		}
		
		public System.Data.Linq.Table<REGISTRATION> REGISTRATIONs
		{
			get
			{
				return this.GetTable<REGISTRATION>();
			}
		}
		
		public System.Data.Linq.Table<STUDENT> STUDENTs
		{
			get
			{
				return this.GetTable<STUDENT>();
			}
		}
		
		public System.Data.Linq.Table<STUDENT_FEEDBACK> STUDENT_FEEDBACKs
		{
			get
			{
				return this.GetTable<STUDENT_FEEDBACK>();
			}
		}
		
		public System.Data.Linq.Table<TEACHER> TEACHERs
		{
			get
			{
				return this.GetTable<TEACHER>();
			}
		}
		
		public System.Data.Linq.Table<USER_ACCOUNT> USER_ACCOUNTs
		{
			get
			{
				return this.GetTable<USER_ACCOUNT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ATTENDANCE")]
	public partial class ATTENDANCE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AttendanceID;
		
		private int _RegistrationID;
		
		private System.DateTime _ClassDate;
		
		private string _Status;
		
		private EntityRef<REGISTRATION> _REGISTRATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAttendanceIDChanging(int value);
    partial void OnAttendanceIDChanged();
    partial void OnRegistrationIDChanging(int value);
    partial void OnRegistrationIDChanged();
    partial void OnClassDateChanging(System.DateTime value);
    partial void OnClassDateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public ATTENDANCE()
		{
			this._REGISTRATION = default(EntityRef<REGISTRATION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendanceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AttendanceID
		{
			get
			{
				return this._AttendanceID;
			}
			set
			{
				if ((this._AttendanceID != value))
				{
					this.OnAttendanceIDChanging(value);
					this.SendPropertyChanging();
					this._AttendanceID = value;
					this.SendPropertyChanged("AttendanceID");
					this.OnAttendanceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistrationID", DbType="Int NOT NULL")]
		public int RegistrationID
		{
			get
			{
				return this._RegistrationID;
			}
			set
			{
				if ((this._RegistrationID != value))
				{
					if (this._REGISTRATION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRegistrationIDChanging(value);
					this.SendPropertyChanging();
					this._RegistrationID = value;
					this.SendPropertyChanged("RegistrationID");
					this.OnRegistrationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassDate", DbType="Date NOT NULL")]
		public System.DateTime ClassDate
		{
			get
			{
				return this._ClassDate;
			}
			set
			{
				if ((this._ClassDate != value))
				{
					this.OnClassDateChanging(value);
					this.SendPropertyChanging();
					this._ClassDate = value;
					this.SendPropertyChanged("ClassDate");
					this.OnClassDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="REGISTRATION_ATTENDANCE", Storage="_REGISTRATION", ThisKey="RegistrationID", OtherKey="RegistrationID", IsForeignKey=true)]
		public REGISTRATION REGISTRATION
		{
			get
			{
				return this._REGISTRATION.Entity;
			}
			set
			{
				REGISTRATION previousValue = this._REGISTRATION.Entity;
				if (((previousValue != value) 
							|| (this._REGISTRATION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._REGISTRATION.Entity = null;
						previousValue.ATTENDANCEs.Remove(this);
					}
					this._REGISTRATION.Entity = value;
					if ((value != null))
					{
						value.ATTENDANCEs.Add(this);
						this._RegistrationID = value.RegistrationID;
					}
					else
					{
						this._RegistrationID = default(int);
					}
					this.SendPropertyChanged("REGISTRATION");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLASS")]
	public partial class CLASS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ClassID;
		
		private int _ProgramID;
		
		private int _TeacherID;
		
		private int _StatusID;
		
		private string _ClassName;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private EntitySet<CLASS_MATERIAL> _CLASS_MATERIALs;
		
		private EntitySet<CLASS_SCHEDULE> _CLASS_SCHEDULEs;
		
		private EntitySet<REGISTRATION> _REGISTRATIONs;
		
		private EntitySet<STUDENT_FEEDBACK> _STUDENT_FEEDBACKs;
		
		private EntityRef<CLASS_STATUS> _CLASS_STATUS;
		
		private EntityRef<PROGRAM> _PROGRAM;
		
		private EntityRef<TEACHER> _TEACHER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnProgramIDChanging(int value);
    partial void OnProgramIDChanged();
    partial void OnTeacherIDChanging(int value);
    partial void OnTeacherIDChanged();
    partial void OnStatusIDChanging(int value);
    partial void OnStatusIDChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    #endregion
		
		public CLASS()
		{
			this._CLASS_MATERIALs = new EntitySet<CLASS_MATERIAL>(new Action<CLASS_MATERIAL>(this.attach_CLASS_MATERIALs), new Action<CLASS_MATERIAL>(this.detach_CLASS_MATERIALs));
			this._CLASS_SCHEDULEs = new EntitySet<CLASS_SCHEDULE>(new Action<CLASS_SCHEDULE>(this.attach_CLASS_SCHEDULEs), new Action<CLASS_SCHEDULE>(this.detach_CLASS_SCHEDULEs));
			this._REGISTRATIONs = new EntitySet<REGISTRATION>(new Action<REGISTRATION>(this.attach_REGISTRATIONs), new Action<REGISTRATION>(this.detach_REGISTRATIONs));
			this._STUDENT_FEEDBACKs = new EntitySet<STUDENT_FEEDBACK>(new Action<STUDENT_FEEDBACK>(this.attach_STUDENT_FEEDBACKs), new Action<STUDENT_FEEDBACK>(this.detach_STUDENT_FEEDBACKs));
			this._CLASS_STATUS = default(EntityRef<CLASS_STATUS>);
			this._PROGRAM = default(EntityRef<PROGRAM>);
			this._TEACHER = default(EntityRef<TEACHER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", DbType="Int NOT NULL")]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					if (this._PROGRAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProgramIDChanging(value);
					this.SendPropertyChanging();
					this._ProgramID = value;
					this.SendPropertyChanged("ProgramID");
					this.OnProgramIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherID", DbType="Int NOT NULL")]
		public int TeacherID
		{
			get
			{
				return this._TeacherID;
			}
			set
			{
				if ((this._TeacherID != value))
				{
					if (this._TEACHER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTeacherIDChanging(value);
					this.SendPropertyChanging();
					this._TeacherID = value;
					this.SendPropertyChanged("TeacherID");
					this.OnTeacherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int NOT NULL")]
		public int StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					if (this._CLASS_STATUS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStatusIDChanging(value);
					this.SendPropertyChanging();
					this._StatusID = value;
					this.SendPropertyChanged("StatusID");
					this.OnStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this.OnClassNameChanging(value);
					this.SendPropertyChanging();
					this._ClassName = value;
					this.SendPropertyChanged("ClassName");
					this.OnClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_CLASS_MATERIAL", Storage="_CLASS_MATERIALs", ThisKey="ClassID", OtherKey="ClassID")]
		public EntitySet<CLASS_MATERIAL> CLASS_MATERIALs
		{
			get
			{
				return this._CLASS_MATERIALs;
			}
			set
			{
				this._CLASS_MATERIALs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_CLASS_SCHEDULE", Storage="_CLASS_SCHEDULEs", ThisKey="ClassID", OtherKey="ClassID")]
		public EntitySet<CLASS_SCHEDULE> CLASS_SCHEDULEs
		{
			get
			{
				return this._CLASS_SCHEDULEs;
			}
			set
			{
				this._CLASS_SCHEDULEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_REGISTRATION", Storage="_REGISTRATIONs", ThisKey="ClassID", OtherKey="ClassID")]
		public EntitySet<REGISTRATION> REGISTRATIONs
		{
			get
			{
				return this._REGISTRATIONs;
			}
			set
			{
				this._REGISTRATIONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_STUDENT_FEEDBACK", Storage="_STUDENT_FEEDBACKs", ThisKey="ClassID", OtherKey="ClassID")]
		public EntitySet<STUDENT_FEEDBACK> STUDENT_FEEDBACKs
		{
			get
			{
				return this._STUDENT_FEEDBACKs;
			}
			set
			{
				this._STUDENT_FEEDBACKs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_STATUS_CLASS", Storage="_CLASS_STATUS", ThisKey="StatusID", OtherKey="StatusID", IsForeignKey=true)]
		public CLASS_STATUS CLASS_STATUS
		{
			get
			{
				return this._CLASS_STATUS.Entity;
			}
			set
			{
				CLASS_STATUS previousValue = this._CLASS_STATUS.Entity;
				if (((previousValue != value) 
							|| (this._CLASS_STATUS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLASS_STATUS.Entity = null;
						previousValue.CLASSes.Remove(this);
					}
					this._CLASS_STATUS.Entity = value;
					if ((value != null))
					{
						value.CLASSes.Add(this);
						this._StatusID = value.StatusID;
					}
					else
					{
						this._StatusID = default(int);
					}
					this.SendPropertyChanged("CLASS_STATUS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROGRAM_CLASS", Storage="_PROGRAM", ThisKey="ProgramID", OtherKey="ProgramID", IsForeignKey=true)]
		public PROGRAM PROGRAM
		{
			get
			{
				return this._PROGRAM.Entity;
			}
			set
			{
				PROGRAM previousValue = this._PROGRAM.Entity;
				if (((previousValue != value) 
							|| (this._PROGRAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROGRAM.Entity = null;
						previousValue.CLASSes.Remove(this);
					}
					this._PROGRAM.Entity = value;
					if ((value != null))
					{
						value.CLASSes.Add(this);
						this._ProgramID = value.ProgramID;
					}
					else
					{
						this._ProgramID = default(int);
					}
					this.SendPropertyChanged("PROGRAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TEACHER_CLASS", Storage="_TEACHER", ThisKey="TeacherID", OtherKey="TeacherID", IsForeignKey=true)]
		public TEACHER TEACHER
		{
			get
			{
				return this._TEACHER.Entity;
			}
			set
			{
				TEACHER previousValue = this._TEACHER.Entity;
				if (((previousValue != value) 
							|| (this._TEACHER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TEACHER.Entity = null;
						previousValue.CLASSes.Remove(this);
					}
					this._TEACHER.Entity = value;
					if ((value != null))
					{
						value.CLASSes.Add(this);
						this._TeacherID = value.TeacherID;
					}
					else
					{
						this._TeacherID = default(int);
					}
					this.SendPropertyChanged("TEACHER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLASS_MATERIALs(CLASS_MATERIAL entity)
		{
			this.SendPropertyChanging();
			entity.CLASS = this;
		}
		
		private void detach_CLASS_MATERIALs(CLASS_MATERIAL entity)
		{
			this.SendPropertyChanging();
			entity.CLASS = null;
		}
		
		private void attach_CLASS_SCHEDULEs(CLASS_SCHEDULE entity)
		{
			this.SendPropertyChanging();
			entity.CLASS = this;
		}
		
		private void detach_CLASS_SCHEDULEs(CLASS_SCHEDULE entity)
		{
			this.SendPropertyChanging();
			entity.CLASS = null;
		}
		
		private void attach_REGISTRATIONs(REGISTRATION entity)
		{
			this.SendPropertyChanging();
			entity.CLASS = this;
		}
		
		private void detach_REGISTRATIONs(REGISTRATION entity)
		{
			this.SendPropertyChanging();
			entity.CLASS = null;
		}
		
		private void attach_STUDENT_FEEDBACKs(STUDENT_FEEDBACK entity)
		{
			this.SendPropertyChanging();
			entity.CLASS = this;
		}
		
		private void detach_STUDENT_FEEDBACKs(STUDENT_FEEDBACK entity)
		{
			this.SendPropertyChanging();
			entity.CLASS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLASS_MATERIAL")]
	public partial class CLASS_MATERIAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaterialID;
		
		private int _ClassID;
		
		private string _FileName;
		
		private string _FilePath;
		
		private System.Nullable<System.DateTime> _UploadDate;
		
		private EntityRef<CLASS> _CLASS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaterialIDChanging(int value);
    partial void OnMaterialIDChanged();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnFilePathChanging(string value);
    partial void OnFilePathChanged();
    partial void OnUploadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUploadDateChanged();
    #endregion
		
		public CLASS_MATERIAL()
		{
			this._CLASS = default(EntityRef<CLASS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaterialID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaterialID
		{
			get
			{
				return this._MaterialID;
			}
			set
			{
				if ((this._MaterialID != value))
				{
					this.OnMaterialIDChanging(value);
					this.SendPropertyChanging();
					this._MaterialID = value;
					this.SendPropertyChanged("MaterialID");
					this.OnMaterialIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL")]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					if (this._CLASS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilePath", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FilePath
		{
			get
			{
				return this._FilePath;
			}
			set
			{
				if ((this._FilePath != value))
				{
					this.OnFilePathChanging(value);
					this.SendPropertyChanging();
					this._FilePath = value;
					this.SendPropertyChanged("FilePath");
					this.OnFilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UploadDate
		{
			get
			{
				return this._UploadDate;
			}
			set
			{
				if ((this._UploadDate != value))
				{
					this.OnUploadDateChanging(value);
					this.SendPropertyChanging();
					this._UploadDate = value;
					this.SendPropertyChanged("UploadDate");
					this.OnUploadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_CLASS_MATERIAL", Storage="_CLASS", ThisKey="ClassID", OtherKey="ClassID", IsForeignKey=true)]
		public CLASS CLASS
		{
			get
			{
				return this._CLASS.Entity;
			}
			set
			{
				CLASS previousValue = this._CLASS.Entity;
				if (((previousValue != value) 
							|| (this._CLASS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLASS.Entity = null;
						previousValue.CLASS_MATERIALs.Remove(this);
					}
					this._CLASS.Entity = value;
					if ((value != null))
					{
						value.CLASS_MATERIALs.Add(this);
						this._ClassID = value.ClassID;
					}
					else
					{
						this._ClassID = default(int);
					}
					this.SendPropertyChanged("CLASS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLASS_SCHEDULE")]
	public partial class CLASS_SCHEDULE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ScheduleID;
		
		private int _ClassID;
		
		private string _DayOfWeek;
		
		private System.TimeSpan _StartTime;
		
		private System.TimeSpan _EndTime;
		
		private string _Room;
		
		private EntityRef<CLASS> _CLASS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnScheduleIDChanging(int value);
    partial void OnScheduleIDChanged();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnDayOfWeekChanging(string value);
    partial void OnDayOfWeekChanged();
    partial void OnStartTimeChanging(System.TimeSpan value);
    partial void OnStartTimeChanged();
    partial void OnEndTimeChanging(System.TimeSpan value);
    partial void OnEndTimeChanged();
    partial void OnRoomChanging(string value);
    partial void OnRoomChanged();
    #endregion
		
		public CLASS_SCHEDULE()
		{
			this._CLASS = default(EntityRef<CLASS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ScheduleID
		{
			get
			{
				return this._ScheduleID;
			}
			set
			{
				if ((this._ScheduleID != value))
				{
					this.OnScheduleIDChanging(value);
					this.SendPropertyChanging();
					this._ScheduleID = value;
					this.SendPropertyChanged("ScheduleID");
					this.OnScheduleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL")]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					if (this._CLASS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayOfWeek", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DayOfWeek
		{
			get
			{
				return this._DayOfWeek;
			}
			set
			{
				if ((this._DayOfWeek != value))
				{
					this.OnDayOfWeekChanging(value);
					this.SendPropertyChanging();
					this._DayOfWeek = value;
					this.SendPropertyChanged("DayOfWeek");
					this.OnDayOfWeekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="Time NOT NULL")]
		public System.TimeSpan StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="Time NOT NULL")]
		public System.TimeSpan EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room", DbType="NVarChar(50)")]
		public string Room
		{
			get
			{
				return this._Room;
			}
			set
			{
				if ((this._Room != value))
				{
					this.OnRoomChanging(value);
					this.SendPropertyChanging();
					this._Room = value;
					this.SendPropertyChanged("Room");
					this.OnRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_CLASS_SCHEDULE", Storage="_CLASS", ThisKey="ClassID", OtherKey="ClassID", IsForeignKey=true)]
		public CLASS CLASS
		{
			get
			{
				return this._CLASS.Entity;
			}
			set
			{
				CLASS previousValue = this._CLASS.Entity;
				if (((previousValue != value) 
							|| (this._CLASS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLASS.Entity = null;
						previousValue.CLASS_SCHEDULEs.Remove(this);
					}
					this._CLASS.Entity = value;
					if ((value != null))
					{
						value.CLASS_SCHEDULEs.Add(this);
						this._ClassID = value.ClassID;
					}
					else
					{
						this._ClassID = default(int);
					}
					this.SendPropertyChanged("CLASS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLASS_STATUS")]
	public partial class CLASS_STATUS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StatusID;
		
		private string _StatusName;
		
		private EntitySet<CLASS> _CLASSes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStatusIDChanging(int value);
    partial void OnStatusIDChanged();
    partial void OnStatusNameChanging(string value);
    partial void OnStatusNameChanged();
    #endregion
		
		public CLASS_STATUS()
		{
			this._CLASSes = new EntitySet<CLASS>(new Action<CLASS>(this.attach_CLASSes), new Action<CLASS>(this.detach_CLASSes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this.OnStatusIDChanging(value);
					this.SendPropertyChanging();
					this._StatusID = value;
					this.SendPropertyChanged("StatusID");
					this.OnStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StatusName
		{
			get
			{
				return this._StatusName;
			}
			set
			{
				if ((this._StatusName != value))
				{
					this.OnStatusNameChanging(value);
					this.SendPropertyChanging();
					this._StatusName = value;
					this.SendPropertyChanged("StatusName");
					this.OnStatusNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_STATUS_CLASS", Storage="_CLASSes", ThisKey="StatusID", OtherKey="StatusID")]
		public EntitySet<CLASS> CLASSes
		{
			get
			{
				return this._CLASSes;
			}
			set
			{
				this._CLASSes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLASSes(CLASS entity)
		{
			this.SendPropertyChanging();
			entity.CLASS_STATUS = this;
		}
		
		private void detach_CLASSes(CLASS entity)
		{
			this.SendPropertyChanging();
			entity.CLASS_STATUS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONSULTATION")]
	public partial class CONSULTATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ConsultationID;
		
		private string _GuestName;
		
		private string _ContactInformation;
		
		private string _QuestionContent;
		
		private string _RequestStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnConsultationIDChanging(int value);
    partial void OnConsultationIDChanged();
    partial void OnGuestNameChanging(string value);
    partial void OnGuestNameChanged();
    partial void OnContactInformationChanging(string value);
    partial void OnContactInformationChanged();
    partial void OnQuestionContentChanging(string value);
    partial void OnQuestionContentChanged();
    partial void OnRequestStatusChanging(string value);
    partial void OnRequestStatusChanged();
    #endregion
		
		public CONSULTATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsultationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ConsultationID
		{
			get
			{
				return this._ConsultationID;
			}
			set
			{
				if ((this._ConsultationID != value))
				{
					this.OnConsultationIDChanging(value);
					this.SendPropertyChanging();
					this._ConsultationID = value;
					this.SendPropertyChanged("ConsultationID");
					this.OnConsultationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string GuestName
		{
			get
			{
				return this._GuestName;
			}
			set
			{
				if ((this._GuestName != value))
				{
					this.OnGuestNameChanging(value);
					this.SendPropertyChanging();
					this._GuestName = value;
					this.SendPropertyChanged("GuestName");
					this.OnGuestNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactInformation", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ContactInformation
		{
			get
			{
				return this._ContactInformation;
			}
			set
			{
				if ((this._ContactInformation != value))
				{
					this.OnContactInformationChanging(value);
					this.SendPropertyChanging();
					this._ContactInformation = value;
					this.SendPropertyChanged("ContactInformation");
					this.OnContactInformationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionContent", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string QuestionContent
		{
			get
			{
				return this._QuestionContent;
			}
			set
			{
				if ((this._QuestionContent != value))
				{
					this.OnQuestionContentChanging(value);
					this.SendPropertyChanging();
					this._QuestionContent = value;
					this.SendPropertyChanged("QuestionContent");
					this.OnQuestionContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestStatus", DbType="NVarChar(50)")]
		public string RequestStatus
		{
			get
			{
				return this._RequestStatus;
			}
			set
			{
				if ((this._RequestStatus != value))
				{
					this.OnRequestStatusChanging(value);
					this.SendPropertyChanging();
					this._RequestStatus = value;
					this.SendPropertyChanged("RequestStatus");
					this.OnRequestStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAYMENT")]
	public partial class PAYMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PaymentID;
		
		private int _RegistrationID;
		
		private decimal _Amount;
		
		private System.Nullable<System.DateTime> _PaymentDate;
		
		private string _Method;
		
		private string _PaymentStatus;
		
		private EntityRef<REGISTRATION> _REGISTRATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaymentIDChanging(int value);
    partial void OnPaymentIDChanged();
    partial void OnRegistrationIDChanging(int value);
    partial void OnRegistrationIDChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnPaymentDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPaymentDateChanged();
    partial void OnMethodChanging(string value);
    partial void OnMethodChanged();
    partial void OnPaymentStatusChanging(string value);
    partial void OnPaymentStatusChanged();
    #endregion
		
		public PAYMENT()
		{
			this._REGISTRATION = default(EntityRef<REGISTRATION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PaymentID
		{
			get
			{
				return this._PaymentID;
			}
			set
			{
				if ((this._PaymentID != value))
				{
					this.OnPaymentIDChanging(value);
					this.SendPropertyChanging();
					this._PaymentID = value;
					this.SendPropertyChanged("PaymentID");
					this.OnPaymentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistrationID", DbType="Int NOT NULL")]
		public int RegistrationID
		{
			get
			{
				return this._RegistrationID;
			}
			set
			{
				if ((this._RegistrationID != value))
				{
					if (this._REGISTRATION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRegistrationIDChanging(value);
					this.SendPropertyChanging();
					this._RegistrationID = value;
					this.SendPropertyChanged("RegistrationID");
					this.OnRegistrationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaymentDate
		{
			get
			{
				return this._PaymentDate;
			}
			set
			{
				if ((this._PaymentDate != value))
				{
					this.OnPaymentDateChanging(value);
					this.SendPropertyChanging();
					this._PaymentDate = value;
					this.SendPropertyChanged("PaymentDate");
					this.OnPaymentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Method", DbType="NVarChar(50)")]
		public string Method
		{
			get
			{
				return this._Method;
			}
			set
			{
				if ((this._Method != value))
				{
					this.OnMethodChanging(value);
					this.SendPropertyChanging();
					this._Method = value;
					this.SendPropertyChanged("Method");
					this.OnMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentStatus", DbType="NVarChar(50)")]
		public string PaymentStatus
		{
			get
			{
				return this._PaymentStatus;
			}
			set
			{
				if ((this._PaymentStatus != value))
				{
					this.OnPaymentStatusChanging(value);
					this.SendPropertyChanging();
					this._PaymentStatus = value;
					this.SendPropertyChanged("PaymentStatus");
					this.OnPaymentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="REGISTRATION_PAYMENT", Storage="_REGISTRATION", ThisKey="RegistrationID", OtherKey="RegistrationID", IsForeignKey=true)]
		public REGISTRATION REGISTRATION
		{
			get
			{
				return this._REGISTRATION.Entity;
			}
			set
			{
				REGISTRATION previousValue = this._REGISTRATION.Entity;
				if (((previousValue != value) 
							|| (this._REGISTRATION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._REGISTRATION.Entity = null;
						previousValue.PAYMENTs.Remove(this);
					}
					this._REGISTRATION.Entity = value;
					if ((value != null))
					{
						value.PAYMENTs.Add(this);
						this._RegistrationID = value.RegistrationID;
					}
					else
					{
						this._RegistrationID = default(int);
					}
					this.SendPropertyChanged("REGISTRATION");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PLACEMENT_TEST")]
	public partial class PLACEMENT_TEST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TestID;
		
		private int _StudentID;
		
		private System.DateTime _TestDate;
		
		private System.TimeSpan _TestTime;
		
		private string _Level;
		
		private string _ResultScore;
		
		private string _Status;
		
		private EntityRef<STUDENT> _STUDENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestIDChanging(int value);
    partial void OnTestIDChanged();
    partial void OnStudentIDChanging(int value);
    partial void OnStudentIDChanged();
    partial void OnTestDateChanging(System.DateTime value);
    partial void OnTestDateChanged();
    partial void OnTestTimeChanging(System.TimeSpan value);
    partial void OnTestTimeChanged();
    partial void OnLevelChanging(string value);
    partial void OnLevelChanged();
    partial void OnResultScoreChanging(string value);
    partial void OnResultScoreChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public PLACEMENT_TEST()
		{
			this._STUDENT = default(EntityRef<STUDENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TestID
		{
			get
			{
				return this._TestID;
			}
			set
			{
				if ((this._TestID != value))
				{
					this.OnTestIDChanging(value);
					this.SendPropertyChanging();
					this._TestID = value;
					this.SendPropertyChanged("TestID");
					this.OnTestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Int NOT NULL")]
		public int StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					if (this._STUDENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestDate", DbType="Date NOT NULL")]
		public System.DateTime TestDate
		{
			get
			{
				return this._TestDate;
			}
			set
			{
				if ((this._TestDate != value))
				{
					this.OnTestDateChanging(value);
					this.SendPropertyChanging();
					this._TestDate = value;
					this.SendPropertyChanged("TestDate");
					this.OnTestDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestTime", DbType="Time NOT NULL")]
		public System.TimeSpan TestTime
		{
			get
			{
				return this._TestTime;
			}
			set
			{
				if ((this._TestTime != value))
				{
					this.OnTestTimeChanging(value);
					this.SendPropertyChanging();
					this._TestTime = value;
					this.SendPropertyChanged("TestTime");
					this.OnTestTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="NVarChar(50)")]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultScore", DbType="NVarChar(50)")]
		public string ResultScore
		{
			get
			{
				return this._ResultScore;
			}
			set
			{
				if ((this._ResultScore != value))
				{
					this.OnResultScoreChanging(value);
					this.SendPropertyChanging();
					this._ResultScore = value;
					this.SendPropertyChanged("ResultScore");
					this.OnResultScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STUDENT_PLACEMENT_TEST", Storage="_STUDENT", ThisKey="StudentID", OtherKey="StudentID", IsForeignKey=true)]
		public STUDENT STUDENT
		{
			get
			{
				return this._STUDENT.Entity;
			}
			set
			{
				STUDENT previousValue = this._STUDENT.Entity;
				if (((previousValue != value) 
							|| (this._STUDENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STUDENT.Entity = null;
						previousValue.PLACEMENT_TESTs.Remove(this);
					}
					this._STUDENT.Entity = value;
					if ((value != null))
					{
						value.PLACEMENT_TESTs.Add(this);
						this._StudentID = value.StudentID;
					}
					else
					{
						this._StudentID = default(int);
					}
					this.SendPropertyChanged("STUDENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROGRAM")]
	public partial class PROGRAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProgramID;
		
		private string _ProgramName;
		
		private string _Description;
		
		private string _OutputStandard;
		
		private string _Level;
		
		private string _Duration;
		
		private decimal _Fee;
		
		private string _ImageURL;
		
		private System.Nullable<bool> _IsActive;
		
		private EntitySet<CLASS> _CLASSes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProgramIDChanging(int value);
    partial void OnProgramIDChanged();
    partial void OnProgramNameChanging(string value);
    partial void OnProgramNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnOutputStandardChanging(string value);
    partial void OnOutputStandardChanged();
    partial void OnLevelChanging(string value);
    partial void OnLevelChanged();
    partial void OnDurationChanging(string value);
    partial void OnDurationChanged();
    partial void OnFeeChanging(decimal value);
    partial void OnFeeChanged();
    partial void OnImageURLChanging(string value);
    partial void OnImageURLChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public PROGRAM()
		{
			this._CLASSes = new EntitySet<CLASS>(new Action<CLASS>(this.attach_CLASSes), new Action<CLASS>(this.detach_CLASSes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this.OnProgramIDChanging(value);
					this.SendPropertyChanging();
					this._ProgramID = value;
					this.SendPropertyChanged("ProgramID");
					this.OnProgramIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string ProgramName
		{
			get
			{
				return this._ProgramName;
			}
			set
			{
				if ((this._ProgramName != value))
				{
					this.OnProgramNameChanging(value);
					this.SendPropertyChanging();
					this._ProgramName = value;
					this.SendPropertyChanged("ProgramName");
					this.OnProgramNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutputStandard", DbType="NVarChar(255)")]
		public string OutputStandard
		{
			get
			{
				return this._OutputStandard;
			}
			set
			{
				if ((this._OutputStandard != value))
				{
					this.OnOutputStandardChanging(value);
					this.SendPropertyChanging();
					this._OutputStandard = value;
					this.SendPropertyChanged("OutputStandard");
					this.OnOutputStandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="NVarChar(50)")]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="NVarChar(50)")]
		public string Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee", DbType="Decimal(18,2) NOT NULL")]
		public decimal Fee
		{
			get
			{
				return this._Fee;
			}
			set
			{
				if ((this._Fee != value))
				{
					this.OnFeeChanging(value);
					this.SendPropertyChanging();
					this._Fee = value;
					this.SendPropertyChanged("Fee");
					this.OnFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageURL", DbType="NVarChar(255)")]
		public string ImageURL
		{
			get
			{
				return this._ImageURL;
			}
			set
			{
				if ((this._ImageURL != value))
				{
					this.OnImageURLChanging(value);
					this.SendPropertyChanging();
					this._ImageURL = value;
					this.SendPropertyChanged("ImageURL");
					this.OnImageURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROGRAM_CLASS", Storage="_CLASSes", ThisKey="ProgramID", OtherKey="ProgramID")]
		public EntitySet<CLASS> CLASSes
		{
			get
			{
				return this._CLASSes;
			}
			set
			{
				this._CLASSes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLASSes(CLASS entity)
		{
			this.SendPropertyChanging();
			entity.PROGRAM = this;
		}
		
		private void detach_CLASSes(CLASS entity)
		{
			this.SendPropertyChanging();
			entity.PROGRAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REGISTRATION")]
	public partial class REGISTRATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegistrationID;
		
		private int _StudentID;
		
		private int _ClassID;
		
		private System.Nullable<System.DateTime> _RegistrationDate;
		
		private string _RegStatus;
		
		private EntitySet<ATTENDANCE> _ATTENDANCEs;
		
		private EntitySet<PAYMENT> _PAYMENTs;
		
		private EntityRef<CLASS> _CLASS;
		
		private EntityRef<STUDENT> _STUDENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegistrationIDChanging(int value);
    partial void OnRegistrationIDChanged();
    partial void OnStudentIDChanging(int value);
    partial void OnStudentIDChanged();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnRegistrationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegistrationDateChanged();
    partial void OnRegStatusChanging(string value);
    partial void OnRegStatusChanged();
    #endregion
		
		public REGISTRATION()
		{
			this._ATTENDANCEs = new EntitySet<ATTENDANCE>(new Action<ATTENDANCE>(this.attach_ATTENDANCEs), new Action<ATTENDANCE>(this.detach_ATTENDANCEs));
			this._PAYMENTs = new EntitySet<PAYMENT>(new Action<PAYMENT>(this.attach_PAYMENTs), new Action<PAYMENT>(this.detach_PAYMENTs));
			this._CLASS = default(EntityRef<CLASS>);
			this._STUDENT = default(EntityRef<STUDENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistrationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RegistrationID
		{
			get
			{
				return this._RegistrationID;
			}
			set
			{
				if ((this._RegistrationID != value))
				{
					this.OnRegistrationIDChanging(value);
					this.SendPropertyChanging();
					this._RegistrationID = value;
					this.SendPropertyChanged("RegistrationID");
					this.OnRegistrationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Int NOT NULL")]
		public int StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					if (this._STUDENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL")]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					if (this._CLASS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistrationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegistrationDate
		{
			get
			{
				return this._RegistrationDate;
			}
			set
			{
				if ((this._RegistrationDate != value))
				{
					this.OnRegistrationDateChanging(value);
					this.SendPropertyChanging();
					this._RegistrationDate = value;
					this.SendPropertyChanged("RegistrationDate");
					this.OnRegistrationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegStatus", DbType="NVarChar(50)")]
		public string RegStatus
		{
			get
			{
				return this._RegStatus;
			}
			set
			{
				if ((this._RegStatus != value))
				{
					this.OnRegStatusChanging(value);
					this.SendPropertyChanging();
					this._RegStatus = value;
					this.SendPropertyChanged("RegStatus");
					this.OnRegStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="REGISTRATION_ATTENDANCE", Storage="_ATTENDANCEs", ThisKey="RegistrationID", OtherKey="RegistrationID")]
		public EntitySet<ATTENDANCE> ATTENDANCEs
		{
			get
			{
				return this._ATTENDANCEs;
			}
			set
			{
				this._ATTENDANCEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="REGISTRATION_PAYMENT", Storage="_PAYMENTs", ThisKey="RegistrationID", OtherKey="RegistrationID")]
		public EntitySet<PAYMENT> PAYMENTs
		{
			get
			{
				return this._PAYMENTs;
			}
			set
			{
				this._PAYMENTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_REGISTRATION", Storage="_CLASS", ThisKey="ClassID", OtherKey="ClassID", IsForeignKey=true)]
		public CLASS CLASS
		{
			get
			{
				return this._CLASS.Entity;
			}
			set
			{
				CLASS previousValue = this._CLASS.Entity;
				if (((previousValue != value) 
							|| (this._CLASS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLASS.Entity = null;
						previousValue.REGISTRATIONs.Remove(this);
					}
					this._CLASS.Entity = value;
					if ((value != null))
					{
						value.REGISTRATIONs.Add(this);
						this._ClassID = value.ClassID;
					}
					else
					{
						this._ClassID = default(int);
					}
					this.SendPropertyChanged("CLASS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STUDENT_REGISTRATION", Storage="_STUDENT", ThisKey="StudentID", OtherKey="StudentID", IsForeignKey=true)]
		public STUDENT STUDENT
		{
			get
			{
				return this._STUDENT.Entity;
			}
			set
			{
				STUDENT previousValue = this._STUDENT.Entity;
				if (((previousValue != value) 
							|| (this._STUDENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STUDENT.Entity = null;
						previousValue.REGISTRATIONs.Remove(this);
					}
					this._STUDENT.Entity = value;
					if ((value != null))
					{
						value.REGISTRATIONs.Add(this);
						this._StudentID = value.StudentID;
					}
					else
					{
						this._StudentID = default(int);
					}
					this.SendPropertyChanged("STUDENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ATTENDANCEs(ATTENDANCE entity)
		{
			this.SendPropertyChanging();
			entity.REGISTRATION = this;
		}
		
		private void detach_ATTENDANCEs(ATTENDANCE entity)
		{
			this.SendPropertyChanging();
			entity.REGISTRATION = null;
		}
		
		private void attach_PAYMENTs(PAYMENT entity)
		{
			this.SendPropertyChanging();
			entity.REGISTRATION = this;
		}
		
		private void detach_PAYMENTs(PAYMENT entity)
		{
			this.SendPropertyChanging();
			entity.REGISTRATION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STUDENT")]
	public partial class STUDENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudentID;
		
		private int _AccountID;
		
		private string _FullName;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private string _PhoneNumber;
		
		private EntitySet<PLACEMENT_TEST> _PLACEMENT_TESTs;
		
		private EntitySet<REGISTRATION> _REGISTRATIONs;
		
		private EntitySet<STUDENT_FEEDBACK> _STUDENT_FEEDBACKs;
		
		private EntityRef<USER_ACCOUNT> _USER_ACCOUNT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentIDChanging(int value);
    partial void OnStudentIDChanged();
    partial void OnAccountIDChanging(int value);
    partial void OnAccountIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public STUDENT()
		{
			this._PLACEMENT_TESTs = new EntitySet<PLACEMENT_TEST>(new Action<PLACEMENT_TEST>(this.attach_PLACEMENT_TESTs), new Action<PLACEMENT_TEST>(this.detach_PLACEMENT_TESTs));
			this._REGISTRATIONs = new EntitySet<REGISTRATION>(new Action<REGISTRATION>(this.attach_REGISTRATIONs), new Action<REGISTRATION>(this.detach_REGISTRATIONs));
			this._STUDENT_FEEDBACKs = new EntitySet<STUDENT_FEEDBACK>(new Action<STUDENT_FEEDBACK>(this.attach_STUDENT_FEEDBACKs), new Action<STUDENT_FEEDBACK>(this.detach_STUDENT_FEEDBACKs));
			this._USER_ACCOUNT = default(EntityRef<USER_ACCOUNT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="Int NOT NULL")]
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					if (this._USER_ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(20)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STUDENT_PLACEMENT_TEST", Storage="_PLACEMENT_TESTs", ThisKey="StudentID", OtherKey="StudentID")]
		public EntitySet<PLACEMENT_TEST> PLACEMENT_TESTs
		{
			get
			{
				return this._PLACEMENT_TESTs;
			}
			set
			{
				this._PLACEMENT_TESTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STUDENT_REGISTRATION", Storage="_REGISTRATIONs", ThisKey="StudentID", OtherKey="StudentID")]
		public EntitySet<REGISTRATION> REGISTRATIONs
		{
			get
			{
				return this._REGISTRATIONs;
			}
			set
			{
				this._REGISTRATIONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STUDENT_STUDENT_FEEDBACK", Storage="_STUDENT_FEEDBACKs", ThisKey="StudentID", OtherKey="StudentID")]
		public EntitySet<STUDENT_FEEDBACK> STUDENT_FEEDBACKs
		{
			get
			{
				return this._STUDENT_FEEDBACKs;
			}
			set
			{
				this._STUDENT_FEEDBACKs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_ACCOUNT_STUDENT", Storage="_USER_ACCOUNT", ThisKey="AccountID", OtherKey="AccountID", IsForeignKey=true)]
		public USER_ACCOUNT USER_ACCOUNT
		{
			get
			{
				return this._USER_ACCOUNT.Entity;
			}
			set
			{
				USER_ACCOUNT previousValue = this._USER_ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._USER_ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USER_ACCOUNT.Entity = null;
						previousValue.STUDENTs.Remove(this);
					}
					this._USER_ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.STUDENTs.Add(this);
						this._AccountID = value.AccountID;
					}
					else
					{
						this._AccountID = default(int);
					}
					this.SendPropertyChanged("USER_ACCOUNT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PLACEMENT_TESTs(PLACEMENT_TEST entity)
		{
			this.SendPropertyChanging();
			entity.STUDENT = this;
		}
		
		private void detach_PLACEMENT_TESTs(PLACEMENT_TEST entity)
		{
			this.SendPropertyChanging();
			entity.STUDENT = null;
		}
		
		private void attach_REGISTRATIONs(REGISTRATION entity)
		{
			this.SendPropertyChanging();
			entity.STUDENT = this;
		}
		
		private void detach_REGISTRATIONs(REGISTRATION entity)
		{
			this.SendPropertyChanging();
			entity.STUDENT = null;
		}
		
		private void attach_STUDENT_FEEDBACKs(STUDENT_FEEDBACK entity)
		{
			this.SendPropertyChanging();
			entity.STUDENT = this;
		}
		
		private void detach_STUDENT_FEEDBACKs(STUDENT_FEEDBACK entity)
		{
			this.SendPropertyChanging();
			entity.STUDENT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STUDENT_FEEDBACK")]
	public partial class STUDENT_FEEDBACK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FeedbackID;
		
		private int _StudentID;
		
		private int _ClassID;
		
		private System.Nullable<int> _Rating;
		
		private string _FeedbackContent;
		
		private System.Nullable<System.DateTime> _FeedbackDate;
		
		private EntityRef<CLASS> _CLASS;
		
		private EntityRef<STUDENT> _STUDENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFeedbackIDChanging(int value);
    partial void OnFeedbackIDChanged();
    partial void OnStudentIDChanging(int value);
    partial void OnStudentIDChanged();
    partial void OnClassIDChanging(int value);
    partial void OnClassIDChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    partial void OnFeedbackContentChanging(string value);
    partial void OnFeedbackContentChanged();
    partial void OnFeedbackDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFeedbackDateChanged();
    #endregion
		
		public STUDENT_FEEDBACK()
		{
			this._CLASS = default(EntityRef<CLASS>);
			this._STUDENT = default(EntityRef<STUDENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FeedbackID
		{
			get
			{
				return this._FeedbackID;
			}
			set
			{
				if ((this._FeedbackID != value))
				{
					this.OnFeedbackIDChanging(value);
					this.SendPropertyChanging();
					this._FeedbackID = value;
					this.SendPropertyChanged("FeedbackID");
					this.OnFeedbackIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Int NOT NULL")]
		public int StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					if (this._STUDENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL")]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					if (this._CLASS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
		public System.Nullable<int> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackContent", DbType="NVarChar(MAX)")]
		public string FeedbackContent
		{
			get
			{
				return this._FeedbackContent;
			}
			set
			{
				if ((this._FeedbackContent != value))
				{
					this.OnFeedbackContentChanging(value);
					this.SendPropertyChanging();
					this._FeedbackContent = value;
					this.SendPropertyChanged("FeedbackContent");
					this.OnFeedbackContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeedbackDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FeedbackDate
		{
			get
			{
				return this._FeedbackDate;
			}
			set
			{
				if ((this._FeedbackDate != value))
				{
					this.OnFeedbackDateChanging(value);
					this.SendPropertyChanging();
					this._FeedbackDate = value;
					this.SendPropertyChanged("FeedbackDate");
					this.OnFeedbackDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLASS_STUDENT_FEEDBACK", Storage="_CLASS", ThisKey="ClassID", OtherKey="ClassID", IsForeignKey=true)]
		public CLASS CLASS
		{
			get
			{
				return this._CLASS.Entity;
			}
			set
			{
				CLASS previousValue = this._CLASS.Entity;
				if (((previousValue != value) 
							|| (this._CLASS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLASS.Entity = null;
						previousValue.STUDENT_FEEDBACKs.Remove(this);
					}
					this._CLASS.Entity = value;
					if ((value != null))
					{
						value.STUDENT_FEEDBACKs.Add(this);
						this._ClassID = value.ClassID;
					}
					else
					{
						this._ClassID = default(int);
					}
					this.SendPropertyChanged("CLASS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STUDENT_STUDENT_FEEDBACK", Storage="_STUDENT", ThisKey="StudentID", OtherKey="StudentID", IsForeignKey=true)]
		public STUDENT STUDENT
		{
			get
			{
				return this._STUDENT.Entity;
			}
			set
			{
				STUDENT previousValue = this._STUDENT.Entity;
				if (((previousValue != value) 
							|| (this._STUDENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STUDENT.Entity = null;
						previousValue.STUDENT_FEEDBACKs.Remove(this);
					}
					this._STUDENT.Entity = value;
					if ((value != null))
					{
						value.STUDENT_FEEDBACKs.Add(this);
						this._StudentID = value.StudentID;
					}
					else
					{
						this._StudentID = default(int);
					}
					this.SendPropertyChanged("STUDENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEACHER")]
	public partial class TEACHER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TeacherID;
		
		private int _AccountID;
		
		private string _FullName;
		
		private string _Expertise;
		
		private EntitySet<CLASS> _CLASSes;
		
		private EntityRef<USER_ACCOUNT> _USER_ACCOUNT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeacherIDChanging(int value);
    partial void OnTeacherIDChanged();
    partial void OnAccountIDChanging(int value);
    partial void OnAccountIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnExpertiseChanging(string value);
    partial void OnExpertiseChanged();
    #endregion
		
		public TEACHER()
		{
			this._CLASSes = new EntitySet<CLASS>(new Action<CLASS>(this.attach_CLASSes), new Action<CLASS>(this.detach_CLASSes));
			this._USER_ACCOUNT = default(EntityRef<USER_ACCOUNT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TeacherID
		{
			get
			{
				return this._TeacherID;
			}
			set
			{
				if ((this._TeacherID != value))
				{
					this.OnTeacherIDChanging(value);
					this.SendPropertyChanging();
					this._TeacherID = value;
					this.SendPropertyChanged("TeacherID");
					this.OnTeacherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="Int NOT NULL")]
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					if (this._USER_ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expertise", DbType="NVarChar(255)")]
		public string Expertise
		{
			get
			{
				return this._Expertise;
			}
			set
			{
				if ((this._Expertise != value))
				{
					this.OnExpertiseChanging(value);
					this.SendPropertyChanging();
					this._Expertise = value;
					this.SendPropertyChanged("Expertise");
					this.OnExpertiseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TEACHER_CLASS", Storage="_CLASSes", ThisKey="TeacherID", OtherKey="TeacherID")]
		public EntitySet<CLASS> CLASSes
		{
			get
			{
				return this._CLASSes;
			}
			set
			{
				this._CLASSes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_ACCOUNT_TEACHER", Storage="_USER_ACCOUNT", ThisKey="AccountID", OtherKey="AccountID", IsForeignKey=true)]
		public USER_ACCOUNT USER_ACCOUNT
		{
			get
			{
				return this._USER_ACCOUNT.Entity;
			}
			set
			{
				USER_ACCOUNT previousValue = this._USER_ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._USER_ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USER_ACCOUNT.Entity = null;
						previousValue.TEACHERs.Remove(this);
					}
					this._USER_ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.TEACHERs.Add(this);
						this._AccountID = value.AccountID;
					}
					else
					{
						this._AccountID = default(int);
					}
					this.SendPropertyChanged("USER_ACCOUNT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLASSes(CLASS entity)
		{
			this.SendPropertyChanging();
			entity.TEACHER = this;
		}
		
		private void detach_CLASSes(CLASS entity)
		{
			this.SendPropertyChanging();
			entity.TEACHER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USER_ACCOUNT")]
	public partial class USER_ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AccountID;
		
		private string _Email;
		
		private string _PasswordHash;
		
		private string _Role;
		
		private string _Avatar;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<int> _FailedLoginAttempts;
		
		private System.Nullable<bool> _IsLockedOut;
		
		private EntitySet<STUDENT> _STUDENTs;
		
		private EntitySet<TEACHER> _TEACHERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIDChanging(int value);
    partial void OnAccountIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnAvatarChanging(string value);
    partial void OnAvatarChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnFailedLoginAttemptsChanging(System.Nullable<int> value);
    partial void OnFailedLoginAttemptsChanged();
    partial void OnIsLockedOutChanging(System.Nullable<bool> value);
    partial void OnIsLockedOutChanged();
    #endregion
		
		public USER_ACCOUNT()
		{
			this._STUDENTs = new EntitySet<STUDENT>(new Action<STUDENT>(this.attach_STUDENTs), new Action<STUDENT>(this.detach_STUDENTs));
			this._TEACHERs = new EntitySet<TEACHER>(new Action<TEACHER>(this.attach_TEACHERs), new Action<TEACHER>(this.detach_TEACHERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="NVarChar(255)")]
		public string Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedLoginAttempts", DbType="Int")]
		public System.Nullable<int> FailedLoginAttempts
		{
			get
			{
				return this._FailedLoginAttempts;
			}
			set
			{
				if ((this._FailedLoginAttempts != value))
				{
					this.OnFailedLoginAttemptsChanging(value);
					this.SendPropertyChanging();
					this._FailedLoginAttempts = value;
					this.SendPropertyChanged("FailedLoginAttempts");
					this.OnFailedLoginAttemptsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLockedOut", DbType="Bit")]
		public System.Nullable<bool> IsLockedOut
		{
			get
			{
				return this._IsLockedOut;
			}
			set
			{
				if ((this._IsLockedOut != value))
				{
					this.OnIsLockedOutChanging(value);
					this.SendPropertyChanging();
					this._IsLockedOut = value;
					this.SendPropertyChanged("IsLockedOut");
					this.OnIsLockedOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_ACCOUNT_STUDENT", Storage="_STUDENTs", ThisKey="AccountID", OtherKey="AccountID")]
		public EntitySet<STUDENT> STUDENTs
		{
			get
			{
				return this._STUDENTs;
			}
			set
			{
				this._STUDENTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_ACCOUNT_TEACHER", Storage="_TEACHERs", ThisKey="AccountID", OtherKey="AccountID")]
		public EntitySet<TEACHER> TEACHERs
		{
			get
			{
				return this._TEACHERs;
			}
			set
			{
				this._TEACHERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_STUDENTs(STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.USER_ACCOUNT = this;
		}
		
		private void detach_STUDENTs(STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.USER_ACCOUNT = null;
		}
		
		private void attach_TEACHERs(TEACHER entity)
		{
			this.SendPropertyChanging();
			entity.USER_ACCOUNT = this;
		}
		
		private void detach_TEACHERs(TEACHER entity)
		{
			this.SendPropertyChanging();
			entity.USER_ACCOUNT = null;
		}
	}
}
#pragma warning restore 1591
